<a href="https://colab.research.google.com/github/muratkakun/Machine-Learning/blob/master/HW4_5(Deep_Learning).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW4-5

### Q- 1 ) Load and plot few example in MNIST-CLUTTERED. (It is MNIST on cluttered bg)

In [0]:
import numpy as np
b = np.load('mnist_cluttered_60x60_6distortions_test_only.npz', 'r')


In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
print(b.files)
arr = b['y']
print(arr.shape)
print(arr)
print(arr[arr==1])


['x', 'y']
(10000,)
[3 9 4 ... 6 3 5]
[1 1 1 ... 1 1 1]


Divide data into train and test splits. Make sure all labels are represented.

In [8]:
import tensorflow as tf
x_all = b['x']
y_all = b['y']
x_train = x_all[0:500:1]
y_train = y_all[0:500:1]
x_test = x_all[500:1000:1]
y_test = y_all[500:1000:1]

print(x_train)
print(y_train)

print(x_test)
print(y_test)

print(x_train.shape)
print(x_test.shape)




[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[3 9 4 0 6 1 8 6 1 7 9 9 8 6 3 6 3 4 7 4 4 0 5 9 0 5 5 8 5 2 1 5 4 1 9 1 3
 2 0 0 3 2 0 2 9 9 7 1 6 5 8 8 1 2 4 1 8 2 8 1 9 5 9 8 8 1 5 2 9 0 5 6 6 9
 6 1 3 0 1 1 5 1 2 7 1 9 1 7 2 7 6 0 5 7 7 4 4 4 1 1 6 6 1 3 7 8 6 9 8 5 5
 8 1 5 8 5 9 2 0 5 4 4 7 9 2 8 8 8 5 4 1 2 5 6 5 9 3 4 8 2 7 4 3 5 9 0 7 3
 1 9 5 8 7 6 9 3 0 0 3 2 4 6 5 5 6 8 7 7 1 0 5 0 8 3 1 1 6 2 0 7 0 1 3 5 0
 8 9 1 4 1 1 5 7 9 4 5 9 9 8 9 6 1 4 6 0 0 4 6 8 1 8 1 6 7 5 2 2 2 3 7 1 4
 0 9 9 2 0 4 6 9 1 2 3 6 6 1 2 6 5 9 3 6 0 2 3 6 8 9 2 6 4 8 6 1 1 0 6 3 7
 8 2 0 4 8 9 4 5 6 7 4 3 1 5 7 4 1 5 1 4 4 0 8 6 3 7 8 7 2 0 1 4 1 6 0 0 7
 8 7 1 2 3 7 6 8 0 8 4 1 5 0 7 8 4 3 6 1 2 1 3 6 1 9 2 4 9 0 3 6 9 3 7 6 8
 1 6 0 3 0 1 7 6 1 3 9 0 1 0 9 1 3 2 3 9 9 2 0 6 6 5 9 2 4 7 4 6 4 3 6 5 8
 6 9 3 7 9 2 0 2 8 4 1 7 9 5 1 2 8 2 9 2 8 3 0 9 3 0 2 5 7 6 4 8 7 9 4 0 7
 6 2 0 5 3 5 9 4 4 

### Q-2) Create a 2-hidden layer network. (Input-800-800-Output)

In [32]:
from sklearn.metrics import accuracy_score
feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(x_train)


INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmptdh700c0/model.ckpt-2000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 2000 into /tmp/tmptdh700c0/model.ckpt.
INFO:tensorflow:loss = 0.0006761238, step = 2001
INFO:tensorflow:global_step/sec: 29.8383
INFO:tensorflow:loss = 0.0006076277, step = 2101 (3.354 sec)
INFO:tensorflow:global_step/sec: 31.0325
INFO:tensorflow:loss = 0.0005112568, step = 2201 (3.222 sec)
INFO:tensorflow:global_step/sec: 30.7067
INFO:tensorflow:loss = 0.0005468914, step = 2301 (3.256 sec)
INFO:tensorflow:global_step/sec: 30.4122
INFO:tensorflow:loss = 0.00051104923, step = 2401 (3.289 sec)
INFO:tensorflow:global_step/sec: 30.1975
INFO:tensorflow:loss = 0.0005074277, step = 2501 (3.313 sec)
INFO:tensorflow:global_step/sec: 31.8116
INFO:tensorflow:loss = 0.00046980698, step = 2601 (3.141 sec)
INFO:tensorflow:glob

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x7f4fad93cf60>, 'hidden_units': [800, 800], 'feature_columns': (_RealValuedColumn(column_name='', dimension=3600, default_value=None, dtype=tf.float32, normalizer=None),), 'optimizer': None, 'activation_fn': <function elu at 0x7f4fc247c7b8>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

###Q-3) Train and test the performance.  (The accuracy can be 60% 70%). 

10-20 epochs is OK.

In [34]:
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[800, 800], n_classes=10, feature_columns=feature_columns,activation_fn=tf.nn.elu)
dnn_clf.fit(x=x_train, y=y_train, batch_size=50, steps=1000)
y_pred = list(dnn_clf.predict(x_test))
#print(accuracy_score(y_test, y_pred))
print("----------ELU----------------")
dnn_clf.evaluate(x_test, y_test)


INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpmkhgjg32/model.ckpt.
INFO:tensorflow:loss = 2.3426106, step = 1
INFO:tensorflow:global_step/sec: 31.6825
INFO:tensorflow:loss = 0.04528738, step = 101 (3.158 sec)
INFO:tensorflow:global_step/sec: 30.7784
INFO:tensorflow:loss = 0.011730067, step = 201 (3.249 sec)
INFO:tensorflow:global_step/sec: 30.015
INFO:tensorflow:loss = 0.0073736263, step = 301 (3.332 sec)
INFO:tensorflow:global_step/sec: 31.5871
INFO:tensorflow:loss = 0.004838148, step = 401 (3.172 sec)
INFO:tensorflow:global_step/sec: 31.7808
INFO:tensorflow:loss = 0.0037765347, step = 501 (3.145 sec)
INFO:tensorflow:global_step/sec: 32.0325
INFO:tensorflow:loss = 0.002866366, step = 601 (3.117 sec)
INFO:tensorflow:global_step/sec: 31.2114
INFO:tensorflow:loss = 0.002308938, step = 701 (3.209 sec)
INFO:tensorflow:gl

{'accuracy': 0.126, 'global_step': 1000, 'loss': 5.435353}

### Q-4) Compare activation functions. Plot validation accuracy for RELU, ELU, TANH, SELU. Note that each has its own initialization system. For RELU use he_normal or uniform, elu use he_normal, tanh use glorot_uniform, selu use lecun_normal

Comment on the results.

In [37]:
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[800, 800], n_classes=10, feature_columns=feature_columns,activation_fn=tf.nn.relu)
dnn_clf.fit(x=x_train, y=y_train, batch_size=50, steps=1000)
y_pred = list(dnn_clf.predict(x_test))
#print(accuracy_score(y_test, y_pred))
print("----------RELU----------------")
dnn_clf.evaluate(x_test, y_test)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4fadb31b38>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_eval_distribute': None, '_experimental_max_worker_delay_secs': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_protocol': None, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmpcjbl3ifk', '_session_creation_timeout_secs': 7200}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done run

{'accuracy': 0.126, 'global_step': 1000, 'loss': 3.9346783}

In [39]:
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[800, 800], n_classes=10, feature_columns=feature_columns,activation_fn=tf.nn.selu)
dnn_clf.fit(x=x_train, y=y_train, batch_size=50, steps=1000)
y_pred = list(dnn_clf.predict(x_test))
#print(accuracy_score(y_test, y_pred))
print("----------SELU----------------")
dnn_clf.evaluate(x_test, y_test)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4fb3c1f278>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_eval_distribute': None, '_experimental_max_worker_delay_secs': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_protocol': None, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmp476e1agh', '_session_creation_timeout_secs': 7200}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done run

{'accuracy': 0.114, 'global_step': 1000, 'loss': 5.5946264}

In [41]:
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[800, 800], n_classes=10, feature_columns=feature_columns,activation_fn=tf.nn.tanh)
dnn_clf.fit(x=x_train, y=y_train, batch_size=50, steps=1000)
y_pred = list(dnn_clf.predict(x_test))
#print(accuracy_score(y_test, y_pred))
print("----------TANH----------------")
dnn_clf.evaluate(x_test, y_test)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4fad63b390>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_eval_distribute': None, '_experimental_max_worker_delay_secs': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_protocol': None, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmpf35gycm7', '_session_creation_timeout_secs': 7200}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done run

{'accuracy': 0.122, 'global_step': 1000, 'loss': 5.413365}

### 5) For the best and second performing activation repeat all the tests with  SGD, SGD+momentum, SGD+Nesterov, RMSRPOB Adam

Comment on the results


### 6) With the best performing model use Batchnorm and test again

Comment on the result

### 7) With the best performing add Dropout between layers and test again

Comment on the result

### 8) With the Dropout version, apply MonteCarlo Dropout.

Comment on the result.

### 9) Compare LR rate scheduling mehtods.   
## a) fix learning rate, 
## b) decaying learning rate (choose one)
## c) 1cycle schedule choose your n0, n1